# Generated by Django 5.2.4 on 2025-07-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedauth', '0002_followers_likepost_post_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default_user.png', upload_to='profile_images'),
        ),
    ]
