# Generated by Django 5.2.4 on 2025-07-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedauth', '0003_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/default_user.png', upload_to='profile_images'),
        ),
    ]
