services:
  - type: web
    name: lpu-clicks-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn LPUclicks.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: LPUclicks.settings
      - key: DJANGO_SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: lpu-clicks-db
          property: connectionString

# OPTIONAL if you're not using WhiteNoise (but we are, so can remove this)
# staticPublish:
#   - path: /static
#     source: staticfiles
